apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    app.kubernetes.io/name: nginx
  name: nginx-eqs
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: ENV
              value: "DEV"
          image: govindkailas/eqs-nginx:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 6
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 5
          name: nginx
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: server-blocks-paths.conf
                path: server-blocks-paths.conf
            name: nginx-eqs-server-block
          name: nginx-server-block-paths

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nginx
  name: nginx-svc
spec:
  ports:
    - name: http
      nodePort: 31000
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: nginx
  type: NodePort

---
apiVersion: v1
data:
  server-blocks-paths.conf: |-
    include  "/opt/bitnami/nginx/conf/server_blocks/ldap/*.conf";
    include  "/opt/bitnami/nginx/conf/server_blocks/common/*.conf";
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: nginx